name: Multi-Line Shell Comands
on: workflow_dispatch
jobs:
  init-job:
      runs-on: ubuntu-latest
      steps:
        - name: Run multi commands in shell
          run: |
            echo "I love pizza ğŸ•"
            echo "The first letter of my love is I â¤ï¸"
            echo "I like github ğŸ’»ğŸ˜"
            
